query getGroupById($id: String!) {
	getGroupById(id: $id) {
		id
		title
		students {
			id
			lastName
			firstName
			secondName
			birthDate

			certificates {
				id
				startDate
				finishDate
			}
		}
		course {
			id
			number
			departmentId
		}
	}
}
