query getStudentById($id: String!) {
	getStudentById(id: $id) {
		id
		lastName
		firstName
		secondName
		birthDate
		groupId
		isExpelled

		certificates {
			id
			startDate
			finishDate

			healthGroup {
				title
			}

			physicalEducation {
				title
			}
		}
		group {
			id
			title
		}
	}
}
