import '@mantine/core/styles.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import Providers from './providers/providers'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>
					<div className='flex flex-col h-screen'>
						{/* Navbar (на всю ширину, поверх всего) */}
						<header className='bg-gray-800 text-white p-4 flex items-center justify-between w-full fixed top-0 left-0 right-0 h-14 z-50'>
							<h1 className='text-lg font-semibold'>Navbar</h1>
						</header>

						<div className='flex flex-1 pt-14'>
							{/* Sidebar */}
							<aside className='bg-gray-900  text-white p-4 w-64 hidden md:block'>
								<h2 className='text-xl font-bold'>Sidebar</h2>
							</aside>

							{/* Main Content */}
							<main className='p-4 flex-1'>{children}</main>
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
