query getCertificateById($id: String!) {
	getCertificateById(id: $id) {
		id
		startDate
		finishDate
		studentId
		healthGroupId
		physicalEducationId
		student {
			lastName
			firstName
			secondName
			birthDate
			isExpelled
		}
		physicalEducation {
			id
			title
		}
		healthGroup {
			id
			title
		}
	}
}
