query getPhysicalEducationById($id: String!) {
	getPhysicalEducationById(id: $id) {
		id
		title
		certificates {
			id
			startDate
			finishDate
			student {
				id
				lastName
				firstName
				secondName
			}
		}
	}
}
