query GetGroupById($getGroupByIdId: String!) {
    getGroupById(id: $getGroupByIdId) {
        id
        title
        course {
            id
            number
            departmentId
        }
    }
}
