/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminLayoutImport } from './routes/_authenticated/admin/_layout'
import { Route as AuthenticatedAdminLayoutCertificatesIdImport } from './routes/_authenticated/admin/_layout/certificates/$id'
import { Route as AuthenticatedAdminLayoutCertificatesIndexImport } from './routes/_authenticated/admin/_layout/certificates/index'
import { Route as AuthenticatedAdminLayoutCoursesIdImport } from './routes/_authenticated/admin/_layout/courses/$id'
import { Route as AuthenticatedAdminLayoutCoursesIndexImport } from './routes/_authenticated/admin/_layout/courses/index'
import { Route as AuthenticatedAdminLayoutCuratorsIdImport } from './routes/_authenticated/admin/_layout/curators/$id'
import { Route as AuthenticatedAdminLayoutCuratorsIndexImport } from './routes/_authenticated/admin/_layout/curators/index'
import { Route as AuthenticatedAdminLayoutDepartmentsIdImport } from './routes/_authenticated/admin/_layout/departments/$id'
import { Route as AuthenticatedAdminLayoutDepartmentsIndexImport } from './routes/_authenticated/admin/_layout/departments/index'
import { Route as AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdImport } from './routes/_authenticated/admin/_layout/groups-management/health-groups/$id'
import { Route as AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexImport } from './routes/_authenticated/admin/_layout/groups-management/health-groups/index'
import { Route as AuthenticatedAdminLayoutGroupsManagementIndexImport } from './routes/_authenticated/admin/_layout/groups-management/index'
import { Route as AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdImport } from './routes/_authenticated/admin/_layout/groups-management/physical-educations/$id'
import { Route as AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexImport } from './routes/_authenticated/admin/_layout/groups-management/physical-educations/index'
import { Route as AuthenticatedAdminLayoutGroupsIdImport } from './routes/_authenticated/admin/_layout/groups/$id'
import { Route as AuthenticatedAdminLayoutGroupsIndexImport } from './routes/_authenticated/admin/_layout/groups/index'
import { Route as AuthenticatedAdminLayoutProfileIndexImport } from './routes/_authenticated/admin/_layout/profile/index'
import { Route as AuthenticatedAdminLayoutStatisticsIndexImport } from './routes/_authenticated/admin/_layout/statistics/index'
import { Route as AuthenticatedAdminLayoutStudentsIdImport } from './routes/_authenticated/admin/_layout/students/$id'
import { Route as AuthenticatedAdminLayoutStudentsIndexImport } from './routes/_authenticated/admin/_layout/students/index'
import { Route as AuthenticatedCuratorLayoutImport } from './routes/_authenticated/curator/_layout'
import { Route as AuthenticatedCuratorLayoutGroupIdImport } from './routes/_authenticated/curator/_layout/group/$id'
import { Route as PublicAuthLoginIndexImport } from './routes/_public/auth/login/index'
import { Route as PublicIndexImport } from './routes/_public/index'

// Create Virtual Routes

const AuthenticatedCuratorImport = createFileRoute('/_authenticated/curator')()
const AuthenticatedAdminImport = createFileRoute('/_authenticated/admin')()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
	id: '/_authenticated',
	getParentRoute: () => rootRoute
} as any)

const AuthenticatedCuratorRoute = AuthenticatedCuratorImport.update({
	id: '/curator',
	path: '/curator',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
	id: '/admin',
	path: '/admin',
	getParentRoute: () => AuthenticatedRoute
} as any)

const PublicIndexRoute = PublicIndexImport.update({
	id: '/_public/',
	path: '/',
	getParentRoute: () => rootRoute
} as any)

const AuthenticatedCuratorLayoutRoute = AuthenticatedCuratorLayoutImport.update(
	{
		id: '/_layout',
		getParentRoute: () => AuthenticatedCuratorRoute
	} as any
)

const AuthenticatedAdminLayoutRoute = AuthenticatedAdminLayoutImport.update({
	id: '/_layout',
	getParentRoute: () => AuthenticatedAdminRoute
} as any)

const PublicAuthLoginIndexRoute = PublicAuthLoginIndexImport.update({
	id: '/_public/auth/login/',
	path: '/auth/login/',
	getParentRoute: () => rootRoute
} as any)

const AuthenticatedAdminLayoutStudentsIndexRoute =
	AuthenticatedAdminLayoutStudentsIndexImport.update({
		id: '/students/',
		path: '/students/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutStatisticsIndexRoute =
	AuthenticatedAdminLayoutStatisticsIndexImport.update({
		id: '/statistics/',
		path: '/statistics/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutProfileIndexRoute =
	AuthenticatedAdminLayoutProfileIndexImport.update({
		id: '/profile/',
		path: '/profile/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsIndexRoute =
	AuthenticatedAdminLayoutGroupsIndexImport.update({
		id: '/groups/',
		path: '/groups/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsManagementIndexRoute =
	AuthenticatedAdminLayoutGroupsManagementIndexImport.update({
		id: '/groups-management/',
		path: '/groups-management/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutDepartmentsIndexRoute =
	AuthenticatedAdminLayoutDepartmentsIndexImport.update({
		id: '/departments/',
		path: '/departments/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCuratorsIndexRoute =
	AuthenticatedAdminLayoutCuratorsIndexImport.update({
		id: '/curators/',
		path: '/curators/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCoursesIndexRoute =
	AuthenticatedAdminLayoutCoursesIndexImport.update({
		id: '/courses/',
		path: '/courses/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCertificatesIndexRoute =
	AuthenticatedAdminLayoutCertificatesIndexImport.update({
		id: '/certificates/',
		path: '/certificates/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedCuratorLayoutGroupIdRoute =
	AuthenticatedCuratorLayoutGroupIdImport.update({
		id: '/group/$id',
		path: '/group/$id',
		getParentRoute: () => AuthenticatedCuratorLayoutRoute
	} as any)

const AuthenticatedAdminLayoutStudentsIdRoute =
	AuthenticatedAdminLayoutStudentsIdImport.update({
		id: '/students/$id',
		path: '/students/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsIdRoute =
	AuthenticatedAdminLayoutGroupsIdImport.update({
		id: '/groups/$id',
		path: '/groups/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutDepartmentsIdRoute =
	AuthenticatedAdminLayoutDepartmentsIdImport.update({
		id: '/departments/$id',
		path: '/departments/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCuratorsIdRoute =
	AuthenticatedAdminLayoutCuratorsIdImport.update({
		id: '/curators/$id',
		path: '/curators/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCoursesIdRoute =
	AuthenticatedAdminLayoutCoursesIdImport.update({
		id: '/courses/$id',
		path: '/courses/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutCertificatesIdRoute =
	AuthenticatedAdminLayoutCertificatesIdImport.update({
		id: '/certificates/$id',
		path: '/certificates/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute =
	AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexImport.update({
		id: '/groups-management/physical-educations/',
		path: '/groups-management/physical-educations/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute =
	AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexImport.update({
		id: '/groups-management/health-groups/',
		path: '/groups-management/health-groups/',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute =
	AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdImport.update({
		id: '/groups-management/physical-educations/$id',
		path: '/groups-management/physical-educations/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

const AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute =
	AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdImport.update({
		id: '/groups-management/health-groups/$id',
		path: '/groups-management/health-groups/$id',
		getParentRoute: () => AuthenticatedAdminLayoutRoute
	} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/_authenticated': {
			id: '/_authenticated'
			path: ''
			fullPath: ''
			preLoaderRoute: typeof AuthenticatedImport
			parentRoute: typeof rootRoute
		}
		'/_public/': {
			id: '/_public/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof PublicIndexImport
			parentRoute: typeof rootRoute
		}
		'/_authenticated/admin': {
			id: '/_authenticated/admin'
			path: '/admin'
			fullPath: '/admin'
			preLoaderRoute: typeof AuthenticatedAdminImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/admin/_layout': {
			id: '/_authenticated/admin/_layout'
			path: '/admin'
			fullPath: '/admin'
			preLoaderRoute: typeof AuthenticatedAdminLayoutImport
			parentRoute: typeof AuthenticatedAdminRoute
		}
		'/_authenticated/curator': {
			id: '/_authenticated/curator'
			path: '/curator'
			fullPath: '/curator'
			preLoaderRoute: typeof AuthenticatedCuratorImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/curator/_layout': {
			id: '/_authenticated/curator/_layout'
			path: '/curator'
			fullPath: '/curator'
			preLoaderRoute: typeof AuthenticatedCuratorLayoutImport
			parentRoute: typeof AuthenticatedCuratorRoute
		}
		'/_public/auth/login/': {
			id: '/_public/auth/login/'
			path: '/auth/login'
			fullPath: '/auth/login'
			preLoaderRoute: typeof PublicAuthLoginIndexImport
			parentRoute: typeof rootRoute
		}
		'/_authenticated/admin/_layout/certificates/$id': {
			id: '/_authenticated/admin/_layout/certificates/$id'
			path: '/certificates/$id'
			fullPath: '/admin/certificates/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCertificatesIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/courses/$id': {
			id: '/_authenticated/admin/_layout/courses/$id'
			path: '/courses/$id'
			fullPath: '/admin/courses/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCoursesIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/curators/$id': {
			id: '/_authenticated/admin/_layout/curators/$id'
			path: '/curators/$id'
			fullPath: '/admin/curators/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCuratorsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/departments/$id': {
			id: '/_authenticated/admin/_layout/departments/$id'
			path: '/departments/$id'
			fullPath: '/admin/departments/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutDepartmentsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups/$id': {
			id: '/_authenticated/admin/_layout/groups/$id'
			path: '/groups/$id'
			fullPath: '/admin/groups/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/students/$id': {
			id: '/_authenticated/admin/_layout/students/$id'
			path: '/students/$id'
			fullPath: '/admin/students/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutStudentsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/curator/_layout/group/$id': {
			id: '/_authenticated/curator/_layout/group/$id'
			path: '/group/$id'
			fullPath: '/curator/group/$id'
			preLoaderRoute: typeof AuthenticatedCuratorLayoutGroupIdImport
			parentRoute: typeof AuthenticatedCuratorLayoutImport
		}
		'/_authenticated/admin/_layout/certificates/': {
			id: '/_authenticated/admin/_layout/certificates/'
			path: '/certificates'
			fullPath: '/admin/certificates'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCertificatesIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/courses/': {
			id: '/_authenticated/admin/_layout/courses/'
			path: '/courses'
			fullPath: '/admin/courses'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCoursesIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/curators/': {
			id: '/_authenticated/admin/_layout/curators/'
			path: '/curators'
			fullPath: '/admin/curators'
			preLoaderRoute: typeof AuthenticatedAdminLayoutCuratorsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/departments/': {
			id: '/_authenticated/admin/_layout/departments/'
			path: '/departments'
			fullPath: '/admin/departments'
			preLoaderRoute: typeof AuthenticatedAdminLayoutDepartmentsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups-management/': {
			id: '/_authenticated/admin/_layout/groups-management/'
			path: '/groups-management'
			fullPath: '/admin/groups-management'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsManagementIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups/': {
			id: '/_authenticated/admin/_layout/groups/'
			path: '/groups'
			fullPath: '/admin/groups'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/profile/': {
			id: '/_authenticated/admin/_layout/profile/'
			path: '/profile'
			fullPath: '/admin/profile'
			preLoaderRoute: typeof AuthenticatedAdminLayoutProfileIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/statistics/': {
			id: '/_authenticated/admin/_layout/statistics/'
			path: '/statistics'
			fullPath: '/admin/statistics'
			preLoaderRoute: typeof AuthenticatedAdminLayoutStatisticsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/students/': {
			id: '/_authenticated/admin/_layout/students/'
			path: '/students'
			fullPath: '/admin/students'
			preLoaderRoute: typeof AuthenticatedAdminLayoutStudentsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups-management/health-groups/$id': {
			id: '/_authenticated/admin/_layout/groups-management/health-groups/$id'
			path: '/groups-management/health-groups/$id'
			fullPath: '/admin/groups-management/health-groups/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups-management/physical-educations/$id': {
			id: '/_authenticated/admin/_layout/groups-management/physical-educations/$id'
			path: '/groups-management/physical-educations/$id'
			fullPath: '/admin/groups-management/physical-educations/$id'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups-management/health-groups/': {
			id: '/_authenticated/admin/_layout/groups-management/health-groups/'
			path: '/groups-management/health-groups'
			fullPath: '/admin/groups-management/health-groups'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
		'/_authenticated/admin/_layout/groups-management/physical-educations/': {
			id: '/_authenticated/admin/_layout/groups-management/physical-educations/'
			path: '/groups-management/physical-educations'
			fullPath: '/admin/groups-management/physical-educations'
			preLoaderRoute: typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexImport
			parentRoute: typeof AuthenticatedAdminLayoutImport
		}
	}
}

// Create and export the route tree

interface AuthenticatedAdminLayoutRouteChildren {
	AuthenticatedAdminLayoutCertificatesIdRoute: typeof AuthenticatedAdminLayoutCertificatesIdRoute
	AuthenticatedAdminLayoutCoursesIdRoute: typeof AuthenticatedAdminLayoutCoursesIdRoute
	AuthenticatedAdminLayoutCuratorsIdRoute: typeof AuthenticatedAdminLayoutCuratorsIdRoute
	AuthenticatedAdminLayoutDepartmentsIdRoute: typeof AuthenticatedAdminLayoutDepartmentsIdRoute
	AuthenticatedAdminLayoutGroupsIdRoute: typeof AuthenticatedAdminLayoutGroupsIdRoute
	AuthenticatedAdminLayoutStudentsIdRoute: typeof AuthenticatedAdminLayoutStudentsIdRoute
	AuthenticatedAdminLayoutCertificatesIndexRoute: typeof AuthenticatedAdminLayoutCertificatesIndexRoute
	AuthenticatedAdminLayoutCoursesIndexRoute: typeof AuthenticatedAdminLayoutCoursesIndexRoute
	AuthenticatedAdminLayoutCuratorsIndexRoute: typeof AuthenticatedAdminLayoutCuratorsIndexRoute
	AuthenticatedAdminLayoutDepartmentsIndexRoute: typeof AuthenticatedAdminLayoutDepartmentsIndexRoute
	AuthenticatedAdminLayoutGroupsManagementIndexRoute: typeof AuthenticatedAdminLayoutGroupsManagementIndexRoute
	AuthenticatedAdminLayoutGroupsIndexRoute: typeof AuthenticatedAdminLayoutGroupsIndexRoute
	AuthenticatedAdminLayoutProfileIndexRoute: typeof AuthenticatedAdminLayoutProfileIndexRoute
	AuthenticatedAdminLayoutStatisticsIndexRoute: typeof AuthenticatedAdminLayoutStatisticsIndexRoute
	AuthenticatedAdminLayoutStudentsIndexRoute: typeof AuthenticatedAdminLayoutStudentsIndexRoute
	AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute: typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute
	AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute: typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute
	AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute: typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute
	AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute: typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute
}

const AuthenticatedAdminLayoutRouteChildren: AuthenticatedAdminLayoutRouteChildren =
	{
		AuthenticatedAdminLayoutCertificatesIdRoute:
			AuthenticatedAdminLayoutCertificatesIdRoute,
		AuthenticatedAdminLayoutCoursesIdRoute:
			AuthenticatedAdminLayoutCoursesIdRoute,
		AuthenticatedAdminLayoutCuratorsIdRoute:
			AuthenticatedAdminLayoutCuratorsIdRoute,
		AuthenticatedAdminLayoutDepartmentsIdRoute:
			AuthenticatedAdminLayoutDepartmentsIdRoute,
		AuthenticatedAdminLayoutGroupsIdRoute:
			AuthenticatedAdminLayoutGroupsIdRoute,
		AuthenticatedAdminLayoutStudentsIdRoute:
			AuthenticatedAdminLayoutStudentsIdRoute,
		AuthenticatedAdminLayoutCertificatesIndexRoute:
			AuthenticatedAdminLayoutCertificatesIndexRoute,
		AuthenticatedAdminLayoutCoursesIndexRoute:
			AuthenticatedAdminLayoutCoursesIndexRoute,
		AuthenticatedAdminLayoutCuratorsIndexRoute:
			AuthenticatedAdminLayoutCuratorsIndexRoute,
		AuthenticatedAdminLayoutDepartmentsIndexRoute:
			AuthenticatedAdminLayoutDepartmentsIndexRoute,
		AuthenticatedAdminLayoutGroupsManagementIndexRoute:
			AuthenticatedAdminLayoutGroupsManagementIndexRoute,
		AuthenticatedAdminLayoutGroupsIndexRoute:
			AuthenticatedAdminLayoutGroupsIndexRoute,
		AuthenticatedAdminLayoutProfileIndexRoute:
			AuthenticatedAdminLayoutProfileIndexRoute,
		AuthenticatedAdminLayoutStatisticsIndexRoute:
			AuthenticatedAdminLayoutStatisticsIndexRoute,
		AuthenticatedAdminLayoutStudentsIndexRoute:
			AuthenticatedAdminLayoutStudentsIndexRoute,
		AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute:
			AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute,
		AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute:
			AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute,
		AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute:
			AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute,
		AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute:
			AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute
	}

const AuthenticatedAdminLayoutRouteWithChildren =
	AuthenticatedAdminLayoutRoute._addFileChildren(
		AuthenticatedAdminLayoutRouteChildren
	)

interface AuthenticatedAdminRouteChildren {
	AuthenticatedAdminLayoutRoute: typeof AuthenticatedAdminLayoutRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
	AuthenticatedAdminLayoutRoute: AuthenticatedAdminLayoutRouteWithChildren
}

const AuthenticatedAdminRouteWithChildren =
	AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCuratorLayoutRouteChildren {
	AuthenticatedCuratorLayoutGroupIdRoute: typeof AuthenticatedCuratorLayoutGroupIdRoute
}

const AuthenticatedCuratorLayoutRouteChildren: AuthenticatedCuratorLayoutRouteChildren =
	{
		AuthenticatedCuratorLayoutGroupIdRoute:
			AuthenticatedCuratorLayoutGroupIdRoute
	}

const AuthenticatedCuratorLayoutRouteWithChildren =
	AuthenticatedCuratorLayoutRoute._addFileChildren(
		AuthenticatedCuratorLayoutRouteChildren
	)

interface AuthenticatedCuratorRouteChildren {
	AuthenticatedCuratorLayoutRoute: typeof AuthenticatedCuratorLayoutRouteWithChildren
}

const AuthenticatedCuratorRouteChildren: AuthenticatedCuratorRouteChildren = {
	AuthenticatedCuratorLayoutRoute: AuthenticatedCuratorLayoutRouteWithChildren
}

const AuthenticatedCuratorRouteWithChildren =
	AuthenticatedCuratorRoute._addFileChildren(AuthenticatedCuratorRouteChildren)

interface AuthenticatedRouteChildren {
	AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
	AuthenticatedCuratorRoute: typeof AuthenticatedCuratorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
	AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
	AuthenticatedCuratorRoute: AuthenticatedCuratorRouteWithChildren
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
	AuthenticatedRouteChildren
)

export interface FileRoutesByFullPath {
	'': typeof AuthenticatedRouteWithChildren
	'/': typeof PublicIndexRoute
	'/admin': typeof AuthenticatedAdminLayoutRouteWithChildren
	'/curator': typeof AuthenticatedCuratorLayoutRouteWithChildren
	'/auth/login': typeof PublicAuthLoginIndexRoute
	'/admin/certificates/$id': typeof AuthenticatedAdminLayoutCertificatesIdRoute
	'/admin/courses/$id': typeof AuthenticatedAdminLayoutCoursesIdRoute
	'/admin/curators/$id': typeof AuthenticatedAdminLayoutCuratorsIdRoute
	'/admin/departments/$id': typeof AuthenticatedAdminLayoutDepartmentsIdRoute
	'/admin/groups/$id': typeof AuthenticatedAdminLayoutGroupsIdRoute
	'/admin/students/$id': typeof AuthenticatedAdminLayoutStudentsIdRoute
	'/curator/group/$id': typeof AuthenticatedCuratorLayoutGroupIdRoute
	'/admin/certificates': typeof AuthenticatedAdminLayoutCertificatesIndexRoute
	'/admin/courses': typeof AuthenticatedAdminLayoutCoursesIndexRoute
	'/admin/curators': typeof AuthenticatedAdminLayoutCuratorsIndexRoute
	'/admin/departments': typeof AuthenticatedAdminLayoutDepartmentsIndexRoute
	'/admin/groups-management': typeof AuthenticatedAdminLayoutGroupsManagementIndexRoute
	'/admin/groups': typeof AuthenticatedAdminLayoutGroupsIndexRoute
	'/admin/profile': typeof AuthenticatedAdminLayoutProfileIndexRoute
	'/admin/statistics': typeof AuthenticatedAdminLayoutStatisticsIndexRoute
	'/admin/students': typeof AuthenticatedAdminLayoutStudentsIndexRoute
	'/admin/groups-management/health-groups/$id': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute
	'/admin/groups-management/physical-educations/$id': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute
	'/admin/groups-management/health-groups': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute
	'/admin/groups-management/physical-educations': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute
}

export interface FileRoutesByTo {
	'': typeof AuthenticatedRouteWithChildren
	'/': typeof PublicIndexRoute
	'/admin': typeof AuthenticatedAdminLayoutRouteWithChildren
	'/curator': typeof AuthenticatedCuratorLayoutRouteWithChildren
	'/auth/login': typeof PublicAuthLoginIndexRoute
	'/admin/certificates/$id': typeof AuthenticatedAdminLayoutCertificatesIdRoute
	'/admin/courses/$id': typeof AuthenticatedAdminLayoutCoursesIdRoute
	'/admin/curators/$id': typeof AuthenticatedAdminLayoutCuratorsIdRoute
	'/admin/departments/$id': typeof AuthenticatedAdminLayoutDepartmentsIdRoute
	'/admin/groups/$id': typeof AuthenticatedAdminLayoutGroupsIdRoute
	'/admin/students/$id': typeof AuthenticatedAdminLayoutStudentsIdRoute
	'/curator/group/$id': typeof AuthenticatedCuratorLayoutGroupIdRoute
	'/admin/certificates': typeof AuthenticatedAdminLayoutCertificatesIndexRoute
	'/admin/courses': typeof AuthenticatedAdminLayoutCoursesIndexRoute
	'/admin/curators': typeof AuthenticatedAdminLayoutCuratorsIndexRoute
	'/admin/departments': typeof AuthenticatedAdminLayoutDepartmentsIndexRoute
	'/admin/groups-management': typeof AuthenticatedAdminLayoutGroupsManagementIndexRoute
	'/admin/groups': typeof AuthenticatedAdminLayoutGroupsIndexRoute
	'/admin/profile': typeof AuthenticatedAdminLayoutProfileIndexRoute
	'/admin/statistics': typeof AuthenticatedAdminLayoutStatisticsIndexRoute
	'/admin/students': typeof AuthenticatedAdminLayoutStudentsIndexRoute
	'/admin/groups-management/health-groups/$id': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute
	'/admin/groups-management/physical-educations/$id': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute
	'/admin/groups-management/health-groups': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute
	'/admin/groups-management/physical-educations': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/_authenticated': typeof AuthenticatedRouteWithChildren
	'/_public/': typeof PublicIndexRoute
	'/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
	'/_authenticated/admin/_layout': typeof AuthenticatedAdminLayoutRouteWithChildren
	'/_authenticated/curator': typeof AuthenticatedCuratorRouteWithChildren
	'/_authenticated/curator/_layout': typeof AuthenticatedCuratorLayoutRouteWithChildren
	'/_public/auth/login/': typeof PublicAuthLoginIndexRoute
	'/_authenticated/admin/_layout/certificates/$id': typeof AuthenticatedAdminLayoutCertificatesIdRoute
	'/_authenticated/admin/_layout/courses/$id': typeof AuthenticatedAdminLayoutCoursesIdRoute
	'/_authenticated/admin/_layout/curators/$id': typeof AuthenticatedAdminLayoutCuratorsIdRoute
	'/_authenticated/admin/_layout/departments/$id': typeof AuthenticatedAdminLayoutDepartmentsIdRoute
	'/_authenticated/admin/_layout/groups/$id': typeof AuthenticatedAdminLayoutGroupsIdRoute
	'/_authenticated/admin/_layout/students/$id': typeof AuthenticatedAdminLayoutStudentsIdRoute
	'/_authenticated/curator/_layout/group/$id': typeof AuthenticatedCuratorLayoutGroupIdRoute
	'/_authenticated/admin/_layout/certificates/': typeof AuthenticatedAdminLayoutCertificatesIndexRoute
	'/_authenticated/admin/_layout/courses/': typeof AuthenticatedAdminLayoutCoursesIndexRoute
	'/_authenticated/admin/_layout/curators/': typeof AuthenticatedAdminLayoutCuratorsIndexRoute
	'/_authenticated/admin/_layout/departments/': typeof AuthenticatedAdminLayoutDepartmentsIndexRoute
	'/_authenticated/admin/_layout/groups-management/': typeof AuthenticatedAdminLayoutGroupsManagementIndexRoute
	'/_authenticated/admin/_layout/groups/': typeof AuthenticatedAdminLayoutGroupsIndexRoute
	'/_authenticated/admin/_layout/profile/': typeof AuthenticatedAdminLayoutProfileIndexRoute
	'/_authenticated/admin/_layout/statistics/': typeof AuthenticatedAdminLayoutStatisticsIndexRoute
	'/_authenticated/admin/_layout/students/': typeof AuthenticatedAdminLayoutStudentsIndexRoute
	'/_authenticated/admin/_layout/groups-management/health-groups/$id': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIdRoute
	'/_authenticated/admin/_layout/groups-management/physical-educations/$id': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIdRoute
	'/_authenticated/admin/_layout/groups-management/health-groups/': typeof AuthenticatedAdminLayoutGroupsManagementHealthGroupsIndexRoute
	'/_authenticated/admin/_layout/groups-management/physical-educations/': typeof AuthenticatedAdminLayoutGroupsManagementPhysicalEducationsIndexRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths:
		| ''
		| '/'
		| '/admin'
		| '/curator'
		| '/auth/login'
		| '/admin/certificates/$id'
		| '/admin/courses/$id'
		| '/admin/curators/$id'
		| '/admin/departments/$id'
		| '/admin/groups/$id'
		| '/admin/students/$id'
		| '/curator/group/$id'
		| '/admin/certificates'
		| '/admin/courses'
		| '/admin/curators'
		| '/admin/departments'
		| '/admin/groups-management'
		| '/admin/groups'
		| '/admin/profile'
		| '/admin/statistics'
		| '/admin/students'
		| '/admin/groups-management/health-groups/$id'
		| '/admin/groups-management/physical-educations/$id'
		| '/admin/groups-management/health-groups'
		| '/admin/groups-management/physical-educations'
	fileRoutesByTo: FileRoutesByTo
	to:
		| ''
		| '/'
		| '/admin'
		| '/curator'
		| '/auth/login'
		| '/admin/certificates/$id'
		| '/admin/courses/$id'
		| '/admin/curators/$id'
		| '/admin/departments/$id'
		| '/admin/groups/$id'
		| '/admin/students/$id'
		| '/curator/group/$id'
		| '/admin/certificates'
		| '/admin/courses'
		| '/admin/curators'
		| '/admin/departments'
		| '/admin/groups-management'
		| '/admin/groups'
		| '/admin/profile'
		| '/admin/statistics'
		| '/admin/students'
		| '/admin/groups-management/health-groups/$id'
		| '/admin/groups-management/physical-educations/$id'
		| '/admin/groups-management/health-groups'
		| '/admin/groups-management/physical-educations'
	id:
		| '__root__'
		| '/_authenticated'
		| '/_public/'
		| '/_authenticated/admin'
		| '/_authenticated/admin/_layout'
		| '/_authenticated/curator'
		| '/_authenticated/curator/_layout'
		| '/_public/auth/login/'
		| '/_authenticated/admin/_layout/certificates/$id'
		| '/_authenticated/admin/_layout/courses/$id'
		| '/_authenticated/admin/_layout/curators/$id'
		| '/_authenticated/admin/_layout/departments/$id'
		| '/_authenticated/admin/_layout/groups/$id'
		| '/_authenticated/admin/_layout/students/$id'
		| '/_authenticated/curator/_layout/group/$id'
		| '/_authenticated/admin/_layout/certificates/'
		| '/_authenticated/admin/_layout/courses/'
		| '/_authenticated/admin/_layout/curators/'
		| '/_authenticated/admin/_layout/departments/'
		| '/_authenticated/admin/_layout/groups-management/'
		| '/_authenticated/admin/_layout/groups/'
		| '/_authenticated/admin/_layout/profile/'
		| '/_authenticated/admin/_layout/statistics/'
		| '/_authenticated/admin/_layout/students/'
		| '/_authenticated/admin/_layout/groups-management/health-groups/$id'
		| '/_authenticated/admin/_layout/groups-management/physical-educations/$id'
		| '/_authenticated/admin/_layout/groups-management/health-groups/'
		| '/_authenticated/admin/_layout/groups-management/physical-educations/'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
	PublicIndexRoute: typeof PublicIndexRoute
	PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
	AuthenticatedRoute: AuthenticatedRouteWithChildren,
	PublicIndexRoute: PublicIndexRoute,
	PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_public/",
        "/_public/auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin",
        "/_authenticated/curator"
      ]
    },
    "/_public/": {
      "filePath": "_public/index.tsx"
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/_layout"
      ]
    },
    "/_authenticated/admin/_layout": {
      "filePath": "_authenticated/admin/_layout.tsx",
      "parent": "/_authenticated/admin",
      "children": [
        "/_authenticated/admin/_layout/certificates/$id",
        "/_authenticated/admin/_layout/courses/$id",
        "/_authenticated/admin/_layout/curators/$id",
        "/_authenticated/admin/_layout/departments/$id",
        "/_authenticated/admin/_layout/groups/$id",
        "/_authenticated/admin/_layout/students/$id",
        "/_authenticated/admin/_layout/certificates/",
        "/_authenticated/admin/_layout/courses/",
        "/_authenticated/admin/_layout/curators/",
        "/_authenticated/admin/_layout/departments/",
        "/_authenticated/admin/_layout/groups-management/",
        "/_authenticated/admin/_layout/groups/",
        "/_authenticated/admin/_layout/profile/",
        "/_authenticated/admin/_layout/statistics/",
        "/_authenticated/admin/_layout/students/",
        "/_authenticated/admin/_layout/groups-management/health-groups/$id",
        "/_authenticated/admin/_layout/groups-management/physical-educations/$id",
        "/_authenticated/admin/_layout/groups-management/health-groups/",
        "/_authenticated/admin/_layout/groups-management/physical-educations/"
      ]
    },
    "/_authenticated/curator": {
      "filePath": "_authenticated/curator",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/curator/_layout"
      ]
    },
    "/_authenticated/curator/_layout": {
      "filePath": "_authenticated/curator/_layout.tsx",
      "parent": "/_authenticated/curator",
      "children": [
        "/_authenticated/curator/_layout/group/$id"
      ]
    },
    "/_public/auth/login/": {
      "filePath": "_public/auth/login/index.tsx"
    },
    "/_authenticated/admin/_layout/certificates/$id": {
      "filePath": "_authenticated/admin/_layout/certificates/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/courses/$id": {
      "filePath": "_authenticated/admin/_layout/courses/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/curators/$id": {
      "filePath": "_authenticated/admin/_layout/curators/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/departments/$id": {
      "filePath": "_authenticated/admin/_layout/departments/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups/$id": {
      "filePath": "_authenticated/admin/_layout/groups/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/students/$id": {
      "filePath": "_authenticated/admin/_layout/students/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/curator/_layout/group/$id": {
      "filePath": "_authenticated/curator/_layout/group/$id.tsx",
      "parent": "/_authenticated/curator/_layout"
    },
    "/_authenticated/admin/_layout/certificates/": {
      "filePath": "_authenticated/admin/_layout/certificates/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/courses/": {
      "filePath": "_authenticated/admin/_layout/courses/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/curators/": {
      "filePath": "_authenticated/admin/_layout/curators/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/departments/": {
      "filePath": "_authenticated/admin/_layout/departments/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups-management/": {
      "filePath": "_authenticated/admin/_layout/groups-management/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups/": {
      "filePath": "_authenticated/admin/_layout/groups/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/profile/": {
      "filePath": "_authenticated/admin/_layout/profile/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/statistics/": {
      "filePath": "_authenticated/admin/_layout/statistics/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/students/": {
      "filePath": "_authenticated/admin/_layout/students/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups-management/health-groups/$id": {
      "filePath": "_authenticated/admin/_layout/groups-management/health-groups/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups-management/physical-educations/$id": {
      "filePath": "_authenticated/admin/_layout/groups-management/physical-educations/$id.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups-management/health-groups/": {
      "filePath": "_authenticated/admin/_layout/groups-management/health-groups/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    },
    "/_authenticated/admin/_layout/groups-management/physical-educations/": {
      "filePath": "_authenticated/admin/_layout/groups-management/physical-educations/index.tsx",
      "parent": "/_authenticated/admin/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
