/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedCertificatesIdImport } from './routes/_authenticated/certificates/$id'
import { Route as AuthenticatedCertificatesIndexImport } from './routes/_authenticated/certificates/index'
import { Route as AuthenticatedCoursesIdImport } from './routes/_authenticated/courses/$id'
import { Route as AuthenticatedCoursesIndexImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedDepartmentsIdImport } from './routes/_authenticated/departments/$id'
import { Route as AuthenticatedDepartmentsIndexImport } from './routes/_authenticated/departments/index'
import { Route as AuthenticatedGroupsManagementHealthGroupsIdImport } from './routes/_authenticated/groups-management/health-groups/$id'
import { Route as AuthenticatedGroupsManagementHealthGroupsIndexImport } from './routes/_authenticated/groups-management/health-groups/index'
import { Route as AuthenticatedGroupsManagementIndexImport } from './routes/_authenticated/groups-management/index'
import { Route as AuthenticatedGroupsManagementPhysicalEducationsIdImport } from './routes/_authenticated/groups-management/physical-educations/$id'
import { Route as AuthenticatedGroupsManagementPhysicalEducationsIndexImport } from './routes/_authenticated/groups-management/physical-educations/index'
import { Route as AuthenticatedGroupsIdImport } from './routes/_authenticated/groups/$id'
import { Route as AuthenticatedGroupsIndexImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedProfileIndexImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedStatisticsIndexImport } from './routes/_authenticated/statistics/index'
import { Route as AuthenticatedStudentsIdImport } from './routes/_authenticated/students/$id'
import { Route as AuthenticatedStudentsIndexImport } from './routes/_authenticated/students/index'
import { Route as PublicAuthLoginIndexImport } from './routes/_public/auth/login/index'
import { Route as PublicIndexImport } from './routes/_public/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
	id: '/_authenticated',
	getParentRoute: () => rootRoute
} as any)

const PublicIndexRoute = PublicIndexImport.update({
	id: '/_public/',
	path: '/',
	getParentRoute: () => rootRoute
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
	id: '/_admin',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedStudentsIndexRoute = AuthenticatedStudentsIndexImport.update(
	{
		id: '/students/',
		path: '/students/',
		getParentRoute: () => AuthenticatedRoute
	} as any
)

const AuthenticatedStatisticsIndexRoute =
	AuthenticatedStatisticsIndexImport.update({
		id: '/statistics/',
		path: '/statistics/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedProfileIndexRoute = AuthenticatedProfileIndexImport.update({
	id: '/profile/',
	path: '/profile/',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedGroupsIndexRoute = AuthenticatedGroupsIndexImport.update({
	id: '/groups/',
	path: '/groups/',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedGroupsManagementIndexRoute =
	AuthenticatedGroupsManagementIndexImport.update({
		id: '/groups-management/',
		path: '/groups-management/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedDepartmentsIndexRoute =
	AuthenticatedDepartmentsIndexImport.update({
		id: '/departments/',
		path: '/departments/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedCoursesIndexRoute = AuthenticatedCoursesIndexImport.update({
	id: '/courses/',
	path: '/courses/',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedCertificatesIndexRoute =
	AuthenticatedCertificatesIndexImport.update({
		id: '/certificates/',
		path: '/certificates/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdImport.update({
	id: '/students/$id',
	path: '/students/$id',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdImport.update({
	id: '/groups/$id',
	path: '/groups/$id',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedDepartmentsIdRoute = AuthenticatedDepartmentsIdImport.update(
	{
		id: '/departments/$id',
		path: '/departments/$id',
		getParentRoute: () => AuthenticatedRoute
	} as any
)

const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdImport.update({
	id: '/courses/$id',
	path: '/courses/$id',
	getParentRoute: () => AuthenticatedRoute
} as any)

const AuthenticatedCertificatesIdRoute =
	AuthenticatedCertificatesIdImport.update({
		id: '/certificates/$id',
		path: '/certificates/$id',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const PublicAuthLoginIndexRoute = PublicAuthLoginIndexImport.update({
	id: '/_public/auth/login/',
	path: '/auth/login/',
	getParentRoute: () => rootRoute
} as any)

const AuthenticatedGroupsManagementPhysicalEducationsIndexRoute =
	AuthenticatedGroupsManagementPhysicalEducationsIndexImport.update({
		id: '/groups-management/physical-educations/',
		path: '/groups-management/physical-educations/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedGroupsManagementHealthGroupsIndexRoute =
	AuthenticatedGroupsManagementHealthGroupsIndexImport.update({
		id: '/groups-management/health-groups/',
		path: '/groups-management/health-groups/',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedGroupsManagementPhysicalEducationsIdRoute =
	AuthenticatedGroupsManagementPhysicalEducationsIdImport.update({
		id: '/groups-management/physical-educations/$id',
		path: '/groups-management/physical-educations/$id',
		getParentRoute: () => AuthenticatedRoute
	} as any)

const AuthenticatedGroupsManagementHealthGroupsIdRoute =
	AuthenticatedGroupsManagementHealthGroupsIdImport.update({
		id: '/groups-management/health-groups/$id',
		path: '/groups-management/health-groups/$id',
		getParentRoute: () => AuthenticatedRoute
	} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/_authenticated': {
			id: '/_authenticated'
			path: ''
			fullPath: ''
			preLoaderRoute: typeof AuthenticatedImport
			parentRoute: typeof rootRoute
		}
		'/_authenticated/_admin': {
			id: '/_authenticated/_admin'
			path: ''
			fullPath: ''
			preLoaderRoute: typeof AuthenticatedAdminImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_public/': {
			id: '/_public/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof PublicIndexImport
			parentRoute: typeof rootRoute
		}
		'/_authenticated/certificates/$id': {
			id: '/_authenticated/certificates/$id'
			path: '/certificates/$id'
			fullPath: '/certificates/$id'
			preLoaderRoute: typeof AuthenticatedCertificatesIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/courses/$id': {
			id: '/_authenticated/courses/$id'
			path: '/courses/$id'
			fullPath: '/courses/$id'
			preLoaderRoute: typeof AuthenticatedCoursesIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/departments/$id': {
			id: '/_authenticated/departments/$id'
			path: '/departments/$id'
			fullPath: '/departments/$id'
			preLoaderRoute: typeof AuthenticatedDepartmentsIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups/$id': {
			id: '/_authenticated/groups/$id'
			path: '/groups/$id'
			fullPath: '/groups/$id'
			preLoaderRoute: typeof AuthenticatedGroupsIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/students/$id': {
			id: '/_authenticated/students/$id'
			path: '/students/$id'
			fullPath: '/students/$id'
			preLoaderRoute: typeof AuthenticatedStudentsIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/certificates/': {
			id: '/_authenticated/certificates/'
			path: '/certificates'
			fullPath: '/certificates'
			preLoaderRoute: typeof AuthenticatedCertificatesIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/courses/': {
			id: '/_authenticated/courses/'
			path: '/courses'
			fullPath: '/courses'
			preLoaderRoute: typeof AuthenticatedCoursesIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/departments/': {
			id: '/_authenticated/departments/'
			path: '/departments'
			fullPath: '/departments'
			preLoaderRoute: typeof AuthenticatedDepartmentsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups-management/': {
			id: '/_authenticated/groups-management/'
			path: '/groups-management'
			fullPath: '/groups-management'
			preLoaderRoute: typeof AuthenticatedGroupsManagementIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups/': {
			id: '/_authenticated/groups/'
			path: '/groups'
			fullPath: '/groups'
			preLoaderRoute: typeof AuthenticatedGroupsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/profile/': {
			id: '/_authenticated/profile/'
			path: '/profile'
			fullPath: '/profile'
			preLoaderRoute: typeof AuthenticatedProfileIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/statistics/': {
			id: '/_authenticated/statistics/'
			path: '/statistics'
			fullPath: '/statistics'
			preLoaderRoute: typeof AuthenticatedStatisticsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/students/': {
			id: '/_authenticated/students/'
			path: '/students'
			fullPath: '/students'
			preLoaderRoute: typeof AuthenticatedStudentsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups-management/health-groups/$id': {
			id: '/_authenticated/groups-management/health-groups/$id'
			path: '/groups-management/health-groups/$id'
			fullPath: '/groups-management/health-groups/$id'
			preLoaderRoute: typeof AuthenticatedGroupsManagementHealthGroupsIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups-management/physical-educations/$id': {
			id: '/_authenticated/groups-management/physical-educations/$id'
			path: '/groups-management/physical-educations/$id'
			fullPath: '/groups-management/physical-educations/$id'
			preLoaderRoute: typeof AuthenticatedGroupsManagementPhysicalEducationsIdImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups-management/health-groups/': {
			id: '/_authenticated/groups-management/health-groups/'
			path: '/groups-management/health-groups'
			fullPath: '/groups-management/health-groups'
			preLoaderRoute: typeof AuthenticatedGroupsManagementHealthGroupsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_authenticated/groups-management/physical-educations/': {
			id: '/_authenticated/groups-management/physical-educations/'
			path: '/groups-management/physical-educations'
			fullPath: '/groups-management/physical-educations'
			preLoaderRoute: typeof AuthenticatedGroupsManagementPhysicalEducationsIndexImport
			parentRoute: typeof AuthenticatedImport
		}
		'/_public/auth/login/': {
			id: '/_public/auth/login/'
			path: '/auth/login'
			fullPath: '/auth/login'
			preLoaderRoute: typeof PublicAuthLoginIndexImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
	AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
	AuthenticatedCertificatesIdRoute: typeof AuthenticatedCertificatesIdRoute
	AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
	AuthenticatedDepartmentsIdRoute: typeof AuthenticatedDepartmentsIdRoute
	AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
	AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
	AuthenticatedCertificatesIndexRoute: typeof AuthenticatedCertificatesIndexRoute
	AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
	AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
	AuthenticatedGroupsManagementIndexRoute: typeof AuthenticatedGroupsManagementIndexRoute
	AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
	AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
	AuthenticatedStatisticsIndexRoute: typeof AuthenticatedStatisticsIndexRoute
	AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
	AuthenticatedGroupsManagementHealthGroupsIdRoute: typeof AuthenticatedGroupsManagementHealthGroupsIdRoute
	AuthenticatedGroupsManagementPhysicalEducationsIdRoute: typeof AuthenticatedGroupsManagementPhysicalEducationsIdRoute
	AuthenticatedGroupsManagementHealthGroupsIndexRoute: typeof AuthenticatedGroupsManagementHealthGroupsIndexRoute
	AuthenticatedGroupsManagementPhysicalEducationsIndexRoute: typeof AuthenticatedGroupsManagementPhysicalEducationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
	AuthenticatedAdminRoute: AuthenticatedAdminRoute,
	AuthenticatedCertificatesIdRoute: AuthenticatedCertificatesIdRoute,
	AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
	AuthenticatedDepartmentsIdRoute: AuthenticatedDepartmentsIdRoute,
	AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
	AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
	AuthenticatedCertificatesIndexRoute: AuthenticatedCertificatesIndexRoute,
	AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
	AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
	AuthenticatedGroupsManagementIndexRoute:
		AuthenticatedGroupsManagementIndexRoute,
	AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
	AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
	AuthenticatedStatisticsIndexRoute: AuthenticatedStatisticsIndexRoute,
	AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
	AuthenticatedGroupsManagementHealthGroupsIdRoute:
		AuthenticatedGroupsManagementHealthGroupsIdRoute,
	AuthenticatedGroupsManagementPhysicalEducationsIdRoute:
		AuthenticatedGroupsManagementPhysicalEducationsIdRoute,
	AuthenticatedGroupsManagementHealthGroupsIndexRoute:
		AuthenticatedGroupsManagementHealthGroupsIndexRoute,
	AuthenticatedGroupsManagementPhysicalEducationsIndexRoute:
		AuthenticatedGroupsManagementPhysicalEducationsIndexRoute
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
	AuthenticatedRouteChildren
)

export interface FileRoutesByFullPath {
	'': typeof AuthenticatedAdminRoute
	'/': typeof PublicIndexRoute
	'/certificates/$id': typeof AuthenticatedCertificatesIdRoute
	'/courses/$id': typeof AuthenticatedCoursesIdRoute
	'/departments/$id': typeof AuthenticatedDepartmentsIdRoute
	'/groups/$id': typeof AuthenticatedGroupsIdRoute
	'/students/$id': typeof AuthenticatedStudentsIdRoute
	'/certificates': typeof AuthenticatedCertificatesIndexRoute
	'/courses': typeof AuthenticatedCoursesIndexRoute
	'/departments': typeof AuthenticatedDepartmentsIndexRoute
	'/groups-management': typeof AuthenticatedGroupsManagementIndexRoute
	'/groups': typeof AuthenticatedGroupsIndexRoute
	'/profile': typeof AuthenticatedProfileIndexRoute
	'/statistics': typeof AuthenticatedStatisticsIndexRoute
	'/students': typeof AuthenticatedStudentsIndexRoute
	'/groups-management/health-groups/$id': typeof AuthenticatedGroupsManagementHealthGroupsIdRoute
	'/groups-management/physical-educations/$id': typeof AuthenticatedGroupsManagementPhysicalEducationsIdRoute
	'/groups-management/health-groups': typeof AuthenticatedGroupsManagementHealthGroupsIndexRoute
	'/groups-management/physical-educations': typeof AuthenticatedGroupsManagementPhysicalEducationsIndexRoute
	'/auth/login': typeof PublicAuthLoginIndexRoute
}

export interface FileRoutesByTo {
	'': typeof AuthenticatedAdminRoute
	'/': typeof PublicIndexRoute
	'/certificates/$id': typeof AuthenticatedCertificatesIdRoute
	'/courses/$id': typeof AuthenticatedCoursesIdRoute
	'/departments/$id': typeof AuthenticatedDepartmentsIdRoute
	'/groups/$id': typeof AuthenticatedGroupsIdRoute
	'/students/$id': typeof AuthenticatedStudentsIdRoute
	'/certificates': typeof AuthenticatedCertificatesIndexRoute
	'/courses': typeof AuthenticatedCoursesIndexRoute
	'/departments': typeof AuthenticatedDepartmentsIndexRoute
	'/groups-management': typeof AuthenticatedGroupsManagementIndexRoute
	'/groups': typeof AuthenticatedGroupsIndexRoute
	'/profile': typeof AuthenticatedProfileIndexRoute
	'/statistics': typeof AuthenticatedStatisticsIndexRoute
	'/students': typeof AuthenticatedStudentsIndexRoute
	'/groups-management/health-groups/$id': typeof AuthenticatedGroupsManagementHealthGroupsIdRoute
	'/groups-management/physical-educations/$id': typeof AuthenticatedGroupsManagementPhysicalEducationsIdRoute
	'/groups-management/health-groups': typeof AuthenticatedGroupsManagementHealthGroupsIndexRoute
	'/groups-management/physical-educations': typeof AuthenticatedGroupsManagementPhysicalEducationsIndexRoute
	'/auth/login': typeof PublicAuthLoginIndexRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/_authenticated': typeof AuthenticatedRouteWithChildren
	'/_authenticated/_admin': typeof AuthenticatedAdminRoute
	'/_public/': typeof PublicIndexRoute
	'/_authenticated/certificates/$id': typeof AuthenticatedCertificatesIdRoute
	'/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
	'/_authenticated/departments/$id': typeof AuthenticatedDepartmentsIdRoute
	'/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
	'/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
	'/_authenticated/certificates/': typeof AuthenticatedCertificatesIndexRoute
	'/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
	'/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
	'/_authenticated/groups-management/': typeof AuthenticatedGroupsManagementIndexRoute
	'/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
	'/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
	'/_authenticated/statistics/': typeof AuthenticatedStatisticsIndexRoute
	'/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
	'/_authenticated/groups-management/health-groups/$id': typeof AuthenticatedGroupsManagementHealthGroupsIdRoute
	'/_authenticated/groups-management/physical-educations/$id': typeof AuthenticatedGroupsManagementPhysicalEducationsIdRoute
	'/_authenticated/groups-management/health-groups/': typeof AuthenticatedGroupsManagementHealthGroupsIndexRoute
	'/_authenticated/groups-management/physical-educations/': typeof AuthenticatedGroupsManagementPhysicalEducationsIndexRoute
	'/_public/auth/login/': typeof PublicAuthLoginIndexRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths:
		| ''
		| '/'
		| '/certificates/$id'
		| '/courses/$id'
		| '/departments/$id'
		| '/groups/$id'
		| '/students/$id'
		| '/certificates'
		| '/courses'
		| '/departments'
		| '/groups-management'
		| '/groups'
		| '/profile'
		| '/statistics'
		| '/students'
		| '/groups-management/health-groups/$id'
		| '/groups-management/physical-educations/$id'
		| '/groups-management/health-groups'
		| '/groups-management/physical-educations'
		| '/auth/login'
	fileRoutesByTo: FileRoutesByTo
	to:
		| ''
		| '/'
		| '/certificates/$id'
		| '/courses/$id'
		| '/departments/$id'
		| '/groups/$id'
		| '/students/$id'
		| '/certificates'
		| '/courses'
		| '/departments'
		| '/groups-management'
		| '/groups'
		| '/profile'
		| '/statistics'
		| '/students'
		| '/groups-management/health-groups/$id'
		| '/groups-management/physical-educations/$id'
		| '/groups-management/health-groups'
		| '/groups-management/physical-educations'
		| '/auth/login'
	id:
		| '__root__'
		| '/_authenticated'
		| '/_authenticated/_admin'
		| '/_public/'
		| '/_authenticated/certificates/$id'
		| '/_authenticated/courses/$id'
		| '/_authenticated/departments/$id'
		| '/_authenticated/groups/$id'
		| '/_authenticated/students/$id'
		| '/_authenticated/certificates/'
		| '/_authenticated/courses/'
		| '/_authenticated/departments/'
		| '/_authenticated/groups-management/'
		| '/_authenticated/groups/'
		| '/_authenticated/profile/'
		| '/_authenticated/statistics/'
		| '/_authenticated/students/'
		| '/_authenticated/groups-management/health-groups/$id'
		| '/_authenticated/groups-management/physical-educations/$id'
		| '/_authenticated/groups-management/health-groups/'
		| '/_authenticated/groups-management/physical-educations/'
		| '/_public/auth/login/'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
	PublicIndexRoute: typeof PublicIndexRoute
	PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
	AuthenticatedRoute: AuthenticatedRouteWithChildren,
	PublicIndexRoute: PublicIndexRoute,
	PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_public/",
        "/_public/auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_admin",
        "/_authenticated/certificates/$id",
        "/_authenticated/courses/$id",
        "/_authenticated/departments/$id",
        "/_authenticated/groups/$id",
        "/_authenticated/students/$id",
        "/_authenticated/certificates/",
        "/_authenticated/courses/",
        "/_authenticated/departments/",
        "/_authenticated/groups-management/",
        "/_authenticated/groups/",
        "/_authenticated/profile/",
        "/_authenticated/statistics/",
        "/_authenticated/students/",
        "/_authenticated/groups-management/health-groups/$id",
        "/_authenticated/groups-management/physical-educations/$id",
        "/_authenticated/groups-management/health-groups/",
        "/_authenticated/groups-management/physical-educations/"
      ]
    },
    "/_authenticated/_admin": {
      "filePath": "_authenticated/_admin.tsx",
      "parent": "/_authenticated"
    },
    "/_public/": {
      "filePath": "_public/index.tsx"
    },
    "/_authenticated/certificates/$id": {
      "filePath": "_authenticated/certificates/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/courses/$id": {
      "filePath": "_authenticated/courses/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/departments/$id": {
      "filePath": "_authenticated/departments/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups/$id": {
      "filePath": "_authenticated/groups/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/students/$id": {
      "filePath": "_authenticated/students/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/certificates/": {
      "filePath": "_authenticated/certificates/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/courses/": {
      "filePath": "_authenticated/courses/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/departments/": {
      "filePath": "_authenticated/departments/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups-management/": {
      "filePath": "_authenticated/groups-management/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups/": {
      "filePath": "_authenticated/groups/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/statistics/": {
      "filePath": "_authenticated/statistics/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/students/": {
      "filePath": "_authenticated/students/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups-management/health-groups/$id": {
      "filePath": "_authenticated/groups-management/health-groups/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups-management/physical-educations/$id": {
      "filePath": "_authenticated/groups-management/physical-educations/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups-management/health-groups/": {
      "filePath": "_authenticated/groups-management/health-groups/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/groups-management/physical-educations/": {
      "filePath": "_authenticated/groups-management/physical-educations/index.tsx",
      "parent": "/_authenticated"
    },
    "/_public/auth/login/": {
      "filePath": "_public/auth/login/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
