export type * from './certificate.types'
export type * from './course.types'
export type * from './curator.types'
export type * from './department.types'
export type * from './group.types'
export type * from './health-group.types'
export type * from './physical-education.types'
export type * from './student.types'
export * from './user.types'
