export type * from './certificate.types'
export type * from './course.types'
export type * from './curator.types'
export type * from './department.types'
export type * from './group.types'
export type * from './healthGroup.types'
export type * from './physicalEducation.types'
export type * from './student.types'
export * from './user.types'
